name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner for GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Run PyInstaller
      run: |
        .env/bin/pyinstaller --noconfirm --windowed --icon "icon.ico" --name "Shrimp Detector" --add-data "shrimp.jpg:." --add-data "shrimp.mp3:." --add-data "bg.mp3:."  --hidden-import=tkinter --hiden-import=PIL._tkinter_finder main.py
