name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner for GitHub Actions

    steps:
    - name: Upload built executable (optional)
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/main.exe  # Path to the generated .exe
