name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner for GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python (latest version)
      uses: actions/setup-python@v4
      with:
        python-version: 'latest'  # Automatically uses the latest stable version of Python

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Upload built executable (optional)
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/main.exe  # Path to the generated .exe
